// flow-typed signature: a6652c026d2ccb5886bfe5cf5e4690aa
// flow-typed version: <<STUB>>/caniuse-db_v1.0.30000782/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
