// flow-typed signature: 63adcd987ba6ce607892de24e4d2aa9f
// flow-typed version: <<STUB>>/caniuse-db_v^1.0.30000795/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
