// flow-typed signature: 267f3cb942b22042160c3b3fcba5d03b
// flow-typed version: <<STUB>>/caniuse-db_v^1.0.30001002/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "caniuse-db" {
  declare module.exports: any;
}
