// flow-typed signature: db9ff3ce3b851f5be99b4748818df699
// flow-typed version: <<STUB>>/gatsby-paginate_v^1.0.16/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-paginate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-paginate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-paginate/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-paginate/src/index.js' {
  declare module.exports: $Exports<'gatsby-paginate/src/index'>;
}
