// flow-typed signature: fb0c33d802780e50841331eee72ed208
// flow-typed version: <<STUB>>/gatsby-transformer-json_v^2.1.8/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-transformer-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-transformer-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-transformer-json/gatsby-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-transformer-json/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby-transformer-json/gatsby-node'>;
}
declare module 'gatsby-transformer-json/index' {
  declare module.exports: $Exports<'gatsby-transformer-json'>;
}
declare module 'gatsby-transformer-json/index.js' {
  declare module.exports: $Exports<'gatsby-transformer-json'>;
}
