// flow-typed signature: 30c5595a2e54c90a6df057a58dd02f2b
// flow-typed version: <<STUB>>/lokka-transport-http_v^1.6.1/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lokka-transport-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lokka-transport-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lokka-transport-http/dist/index' {
  declare module.exports: any;
}

declare module 'lokka-transport-http/scripts/mocha_runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lokka-transport-http/dist/index.js' {
  declare module.exports: $Exports<'lokka-transport-http/dist/index'>;
}
declare module 'lokka-transport-http/index' {
  declare module.exports: $Exports<'lokka-transport-http'>;
}
declare module 'lokka-transport-http/index.js' {
  declare module.exports: $Exports<'lokka-transport-http'>;
}
declare module 'lokka-transport-http/scripts/mocha_runner.js' {
  declare module.exports: $Exports<'lokka-transport-http/scripts/mocha_runner'>;
}
