// flow-typed signature: e71d4a8b1c0614f58f084cfc0940da03
// flow-typed version: <<STUB>>/prettier-standard_v^9.1.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prettier-standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prettier-standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prettier-standard/src/cli' {
  declare module.exports: any;
}

declare module 'prettier-standard/src/index' {
  declare module.exports: any;
}

declare module 'prettier-standard/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prettier-standard/src/cli.js' {
  declare module.exports: $Exports<'prettier-standard/src/cli'>;
}
declare module 'prettier-standard/src/index.js' {
  declare module.exports: $Exports<'prettier-standard/src/index'>;
}
declare module 'prettier-standard/src/utils.js' {
  declare module.exports: $Exports<'prettier-standard/src/utils'>;
}
