// flow-typed signature: aa27f244aab11a89d37a4265dc3c2122
// flow-typed version: <<STUB>>/scrape-it_v^5.2.0/flow_v0.110.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrape-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "scrape-it" {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "scrape-it/lib" {
  declare module.exports: any;
}

// Filename aliases
declare module "scrape-it/lib/index" {
  declare module.exports: $Exports<"scrape-it/lib">;
}
declare module "scrape-it/lib/index.js" {
  declare module.exports: $Exports<"scrape-it/lib">;
}
