// flow-typed signature: 86bb06c68bc2abcaad058435e9bc3adb
// flow-typed version: <<STUB>>/scrape-it_v^5.1.4/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrape-it'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scrape-it' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scrape-it/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scrape-it/lib/index.js' {
  declare module.exports: $Exports<'scrape-it/lib/index'>;
}
